### Listas
Son contenedores que permiten almacenar una coleccion de objetos en un orden determinado. Se pueden acceder, anadir, o eliminar objetos de forma sencilla. 

In [1]:
L1 = [] # lista vacia

In [2]:
L2 = ['a', 'b', 'i', 'o', 'u'] # lista con valores iniciales

In [3]:
L3 = [2,3,5,7,11] # lista con valores enteros

In [5]:
L4 = ['a', 5, True, "Heiner Romero"] # lista heterogenea con varios tipos de datos diferentes

In [6]:
L4

['a', 5, True, 'Heiner Romero']

In [7]:
L5 = [0] * 10

In [9]:
L5

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [12]:
L4[0] # para llamar elementos de las listas

'a'

In [13]:
L4[1]

5

In [16]:
L5[4] = 3.14667 # Podemos cambiar los elementos mediante igualdad o modificarlos.

In [15]:
L5

[0, 0, 0, 0, 3.14667, 0, 0, 0, 0, 0]

In [17]:
L4[0:2] # Accesos de posiciones multiples, la primera es la 0 y la segunda es la 1 y el 2 es el parametro final 

['a', 5]

In [20]:
L5[1:4] = [1,2,3] # Muy facil y comodo de modificar

In [19]:
L5

[0, 1, 2, 3, 3.14667, 0, 0, 0, 0, 0]

In [21]:
L5.append(8) # append lo que hace es agregar nuevos elementos al final 

In [22]:
L5

[0, 1, 2, 3, 3.14667, 0, 0, 0, 0, 0, 8]

In [23]:
L5.remove(3) # Elimina la primera ocurrencia de objeto 3 de la lista L5

In [25]:
L5

[0, 1, 2, 3.14667, 0, 0, 0, 0, 0, 8]

In [26]:
L5.reverse() # Con este puedo girar la lista

In [27]:
L5

[8, 0, 0, 0, 0, 0, 3.14667, 2, 1, 0]

In [29]:
L5.count(0) # para contar elementos especificos de una lista

6

In [31]:
L5.index(2) # para ver en que posicion se encuentra 

7

In [33]:
len(L5) # Tamano de la lista

10

In [35]:
L = [1,2,3,4,5,6]

In [37]:
L[1::2] # De la posicion 1 en adelante de dos en dos. 

[2, 4, 6]

In [39]:
L[::2] # elementos en posicion impar. 

[1, 3, 5]

In [41]:
L[-1] # devuelve el ultimo elemento

6

In [43]:
8 in L # Para saber si esta adentro de la lista o no

False

### Bucles

Los bucles **for** iteran sobre una coleccion (una lista, un string, un objeto iterable).

In [44]:
for numero in L:
    print(numero)

1
2
3
4
5
6


In [45]:
for numero in L:
    numero = numero *2
    print(numero)

2
4
6
8
10
12


In [57]:
for numero in L:
    numero = numero * 2
    if numero > 5:
        print(numero)
    else: 
        print("Numero menor que cinco: " + str(numero))

Numero menor que cinco: 2
Numero menor que cinco: 4
6
8
10
12


In [64]:
lista = [1,2,3,4,5,6,7,8,9,10]

for numero in lista:
    numero = numero ** 2
    if numero < 10:
        print(numero)
    elif numero == 16:
        numero = numero + 4
        print(numero)
    elif numero >= 20 and numero <= 40:
        numero = numero + 20
        print(numero)
    else: 
        print("Numero fuera de los rangos y el numero es: " + str(numero))

1
4
9
20
45
56
Numero fuera de los rangos y el numero es: 49
Numero fuera de los rangos y el numero es: 64
Numero fuera de los rangos y el numero es: 81
Numero fuera de los rangos y el numero es: 100


In [65]:
for x in range(0,10): # este de rango se usa cuando yo doy un rango o range (10) esto es un bucle for para iterar sobre una lista
    print(x)

0
1
2
3
4
5
6
7
8
9


In [68]:
for letra in "Heiner Romero":
    print(letra)

H
e
i
n
e
r
 
R
o
m
e
r
o


In [71]:
notas = [3.5,6.7,8,9,10,4]
suma = 0
for nota in notas:
    suma = suma + nota
print(suma/len(notas)) # aqui yo uso len para contar la cantidad que tengo, si escribo un numero va a variar

6.866666666666667


### Bucle While

Este bucle se repite hasta que la condicion booleana deja de ser cierta:

In [73]:
count = 0
while count < 10:
    print(count)
    count +=1

0
1
2
3
4
5
6
7
8
9


In [76]:
primos = [2,3,5,7,11,13,17,19,23,29] # esta es una variante del for y es para saber la posicion que tiene 
for idx, p in enumerate(primos):     # ciertos numeros, entonces enumeramos y sabemos el index y el valor
    print(idx, p)

0 2
1 3
2 5
3 7
4 11
5 13
6 17
7 19
8 23
9 29


In [88]:
medias = [2,5,6,6.7,8,4,6,5.6,8.9,9,2.3,3.33,5,6] # muy util para encontrar valores en una lista
for idx, valores in enumerate(medias):
    if valores > 5:
        print(idx, valores)

2 6
3 6.7
4 8
6 6
7 5.6
8 8.9
9 9
13 6


In [92]:
for valores in medias: #Muy util para encontrar valores en un dataframe 
    if valores > 5.00:
        valores = medias.remove(valores)

In [89]:
print(medias)

[2, 5, 6, 6.7, 8, 4, 6, 5.6, 8.9, 9, 2.3, 3.33, 5, 6]


In [93]:
for idx in range(len(primos)):
    print(idx, primos[idx])

0 2
1 3
2 5
3 7
4 11
5 13
6 17
7 19
8 23
9 29


### Ejemplo Criba eratostenes

In [115]:
def criba_eratostenes(n):
    primos = []
    no_primos = []
    
    for i in range(2,n+1):
        if i not in no_primos:
            primos.append(i)
            for j in range(i*i, n+1, i):
                no_primos.append(j)
    return primos

print(criba_eratostenes(120))
print(len(criba_eratostenes(120)))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113]
30


### Tuplas

Es una coleccion de objetos que no puede modificarse (tiene tamanno y contenido fijo). Se utiliza para evitar sobre carga en el uso de la RAM y se declaran con parentesis, no corchetes. 

In [120]:
p1 = (1,)

In [121]:
p1

(1,)

In [118]:
p2 = (1,2,3,4)

In [119]:
p2

(1, 2, 3, 4)

In [124]:
p3 = (1,2,4,"c", "hola", 3.1415)

In [125]:
p3

(1, 2, 4, 'c', 'hola', 3.1415)

In [126]:
p3[0]

1

In [127]:
p3[2:4]

(4, 'c')

In [131]:
a,b,c,d,e,f = p3

In [133]:
a

1

In [134]:
b

2

In [135]:
c

4

In [136]:
d

'c'

In [137]:
e

'hola'

In [138]:
f

3.1415

In [139]:
l3 = list(p3) # puedo cambiar una tupla a una lista

In [140]:
l3

[1, 2, 4, 'c', 'hola', 3.1415]

In [141]:
p5 = tuple(L5) # Puedo cambiar listas a tuplas y viceversa para hacerlas estaticas

In [142]:
p5

(8, 0, 0, 0, 0, 0, 3.14667, 2, 1, 0)

In [143]:
"Hola como esta hoy".split(" ") # con split puedo separar valores y convertirlos en lista

['Hola', 'como', 'esta', 'hoy']

In [144]:
"4,6,7,8,9,3,5".split(",") 

['4', '6', '7', '8', '9', '3', '5']

In [145]:
opcion = "5,8,36,84,24,78,757,5".split(",")

In [146]:
nueva_lista = list(opcion)

In [147]:
nueva_tupla = tuple(opcion)

In [152]:
type(nueva_lista)
print(nueva_lista)

['5', '8', '36', '84', '24', '78', '757', '5']


In [153]:
type(nueva_tupla)
print(nueva_tupla)

('5', '8', '36', '84', '24', '78', '757', '5')


In [151]:
numeros = input("Escribe numeros separados por comas: ")
numerosL = numeros.split(",")
print(numerosL)
numerosT = tuple(numerosL)
print(numerosT)

Escribe numeros separados por comas:  2,4,6,7,3,7,8,3,79,7,85,86,0


['2', '4', '6', '7', '3', '7', '8', '3', '79', '7', '85', '86', '0']
('2', '4', '6', '7', '3', '7', '8', '3', '79', '7', '85', '86', '0')


In [159]:
suma = 0
for numeros in numerosT:
    suma += int(numeros)
print(suma/len(numerosT))

22.846153846153847


### Diccionario

Coleccion no ordenada de pares de valores: claves <-> valores. Se indexa no por posicion, sino utilizando las claves.

In [162]:
nombre = "Heiner"
print("Hola %s"%nombre) # el porcentaje lo que hace es retorna lo que haya en la variable "nombre"

Hola Heiner


In [163]:
nombre = input("Introduzca su nombre")
print("Hola, mucho gusto: %s"%nombre)

Introduzca su nombre Guillermo


Hola, mucho gusto: Guillermo


In [164]:
print("Estos son los numeros primos: %s"%primos) # el "s" es para un string

Estos son los numeros primos: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [165]:
print("Esto es un numero: %d"%suma) # el de es para un numero entero 

Esto es un numero: 297


In [168]:
media = suma/len(numerosT)
print("Esto es un numero decimal: %.0f"%media) # la f es para decimales y hay variantes

Esto es un numero decimal: 23


In [167]:
media = suma/len(numerosT)
print("Esto es un numero decimal: %f"%media) # con decimales

Esto es un numero decimal: 22.846154


In [192]:
edad = {"Ernesto": 23,
       "Maria": 25,
       "Heiner": 27,
       "Katty": 29}

In [176]:
edad["Ernesto"] # para buscar 

23

In [178]:
edad["Katty"] # Para buscar siempre es con corchetes

29

In [179]:
edad["Katty"] = 32

In [180]:
edad["Katty"]

32

In [182]:
edad.keys() # las claves para buscar

dict_keys(['Ernesto', 'Maria', 'Heiner', 'Katty'])

In [184]:
edad.values() # solo los valores de los mismos

dict_values([23, 25, 27, 32])

In [186]:
len(edad)

4

In [187]:
"Pepe" in edad

False

In [188]:
"Katty" in edad

True

In [189]:
"Heiner" not in edad

False

In [193]:
del edad["Ernesto"] # elimino Ernesto

In [194]:
edad

{'Maria': 25, 'Heiner': 27, 'Katty': 29}

In [196]:
notas = {"Heiner": 2.3,
        "Katty": 3.4, 
        "John": False}

In [197]:
notas

{'Heiner': 2.3, 'Katty': 3.4, 'John': False}

### La libreria Numpy y los arrays

In [198]:
import numpy as np

In [199]:
# from numpy import * esta es otra forma de usarlo, pero no es recomendable. 

In [200]:
L1 = [1,2,3,4,5,6,7,8,9,10]

In [203]:
x1 = np.array(L1, dtype= 'float32')
x1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16, float32, float64 (+/- mantiza = 999.9999999e99999)
- complex_, complex64, complex128 (a+bi, a,b $\in$ float_)

In [204]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [205]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [207]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
np.arange(3,12,dtype = np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [209]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [210]:
np.linspace(1.,7.,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [211]:
np.eye(5) # matriz de 5X5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [212]:
x = np.zeros((8,3))

In [213]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [214]:
x.reshape((6,4)) # tiene que ser una distribucion valida para redimensionar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [216]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [217]:
x.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [218]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [220]:
np.ravel(x) # se aplanan las matrices

array([1, 2, 3, 4, 5, 6, 7, 8])

In [223]:
x.flatten() # esto es una COPIA del array colapsado en una dimension

array([1, 2, 3, 4, 5, 6, 7, 8])

In [225]:
x.T # transponer matrices o np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [226]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [227]:
np.resize(x,(5,3)) # empieza a repetir cuando ya no tiene mas numeros que rellenar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios:

1. Crear un array de datos con valores entre 5 y 120

In [231]:
np.arange(5,120)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

2. Crear una matriz 4x4 con los valores de 0 a 15

In [6]:
x = np.arange(16)
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

3. Crear la identidad 7x7

In [234]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

4. Crear un array de 20 elementos y transformalos en una matriz 5x4

In [7]:
b = np.arange(20)
b.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

5. Crear un array con 20 numeros con los valores entre 0 y 5 espaciados de forma uniforme 

In [8]:
np.arange(1,20,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

### Propiedades de los Arrays

In [2]:
import numpy as np

In [11]:
x = np.arange(12)
x = x.reshape((3,4)) # 3 filas y 4 columnas
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
x.ndim # para ver la cantidad de dimensiones

2

In [16]:
x.shape # tamanno de la matriz

(3, 4)

In [18]:
x.size # cantidad de elementos que tiene la matriz, N*M

12

In [19]:
x.dtype

dtype('int64')

In [21]:
x.itemsize # tamano en bits de cada uno de los ementos de la matriz

8

In [22]:
x.data # buffer de la posicion de la memoria en donde se ha almacenado el array

In [23]:
x[2]

array([ 8,  9, 10, 11])

In [24]:
x[2,1]

9

In [28]:
x.shape = (4,3) # para cambiar la forma de la matriz
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
x[1:3, 0:2] # Recordar los indices de inicio y fin

array([[3, 4],
       [6, 7]])

In [33]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
y[3:8] 

array([3, 4, 5, 6, 7])

In [36]:
z = np.arange(10,6, -1) # el -1 representa el salto que hay entre numeros
z

array([10,  9,  8,  7])

In [37]:
y[z] # coincidencias entre matrices

array([10,  9,  8,  7])

In [39]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
x[x>30] # unicamente los numeros que son mayores a 30

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [42]:
condicion = x < 25
condicion

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [44]:
x[condicion] # se puede hacer de ambas formas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
x[12:24] = 1 # para cambiar valores de forma masiva
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
x[13:16] = [6,9,12]  # sustituyendo mediante vectorizacion
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
x.dtype

dtype('int64')

In [56]:
x[5] = 3.1415 # lo conbierte a numero entero y lo va a homologar, porque en numpy solo pueden ir datos homogeneos. 
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#### Ejercicio: modifiicando matriz identidad

In [76]:
a = np.eye(8)
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

#### Como se podria cambiar por un 1 el 0 en la esquina superior derecha e inferior izquierda?

In [77]:
a[7,0] = 1
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1.]])

In [78]:
a[0,7] = 1 
a

array([[1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1.]])

#### Como se podria cambiar todos los 0 de la primera columna por 1?

In [79]:
a[0:7,0] = 1
a

array([[1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1.]])

#### Y ahora con todas las esquinas por 1?

In [81]:
a[0:7,7] = 1
a

array([[1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.]])

In [82]:
a[0,0:7] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.]])

In [83]:
a[7,0:7] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### Copias y Vistas de Arrays

In [85]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
y = x # yo estoy creando una asignacion a otra variable, pero estoy estoy modificando el original

In [92]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
z is x # No es lo mismo, porque es una copia independiente

False

In [98]:
y is x # si es lo mismo, porque es una asignacion

True

In [99]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [103]:
t.shape = (5,2) # no lo cambia 
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [105]:
x # no lo cambia, porque cree una vista y es mejor

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [107]:
ab = x[0:2, 1:3] # esto es una vista en una sub matriz
ab

array([[1, 2],
       [6, 7]])

In [111]:
ab[:] = 5 # lo puedo modificar por completo
ab

array([[5, 5],
       [5, 5]])

In [113]:
z # este no fue modificado

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [115]:
x # pero el X si, entonces es mejor hacer una copia.

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

### Funciones Universales (ufunc)

- Unarias: sqrt, sin, cos, **2
- Binarias: maximum, minimum

In [117]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [122]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [123]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [124]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [125]:
alpha = np.linspace(0,2*np.pi,4)

In [126]:
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [128]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [129]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [130]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [131]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [132]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [133]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [134]:
np.power(x,2) # cuadrado de su propio numero

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [135]:
np.log(x) # ojo el logaritmo de 0 no existe, por eso nos dice inf. 

/Users/heinerleivagmail.com/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [136]:
np.log10(x)

/Users/heinerleivagmail.com/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

$$\sum_{i=1}^n x_i$$

In [137]:
np.sum(x) # este suma pero no discrimina de nulos o NA

45

In [138]:
np.nansum(x) # este elimina los valores NA

45

In [139]:
np.prod(x)

0

In [140]:
np.mean(x)

4.5

In [141]:
np.median(x)

4.5

In [142]:
np.min(x)

0

In [143]:
np.max(x)

9

In [144]:
np.std(x)

2.8722813232690143

In [146]:
np.var(x)

8.25

In [147]:
np.argmin(x) # el indice de la posicion mas pequena

0

In [148]:
np.argmax(x) # el indice de la posicion mas grande

9

In [150]:
np.percentile(x, q=0.95) # percentiles

0.08549999999999999

In [152]:
np.any(x) # devuelve TRUE si alguno de los elementos tiene un TRUE

True

In [153]:
i = np.array([True, True, False, False])

In [154]:
np.any(i)

True

In [155]:
np.all(i) # porque hay unos que son fasle

False

In [158]:
z = np.random.random((3,5))
z

array([[0.04368428, 0.2235175 , 0.64607974, 0.05577356, 0.43460958],
       [0.04120788, 0.40068225, 0.10906546, 0.09470405, 0.5830011 ],
       [0.30958971, 0.45302527, 0.76876277, 0.35016542, 0.50515895]])

In [159]:
z.sum() # esto me suma todos los valores 

5.0190275186004545

In [160]:
z.sum(axis=0) # esto es una suma por columnas

array([0.39448186, 1.07722502, 1.52390798, 0.50064302, 1.52276963])

In [162]:
z.sum(axis=1) # esto es una suma de lineas o filas

array([1.40366466, 1.22866074, 2.38670212])

In [176]:
np.random.seed(2020)
j = np.random.random((3,5)) # esto es para fijar y que los numeros no se me cambien cada vez
j

array([[0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873],
       [0.21695427, 0.27647714, 0.34331559, 0.86215894, 0.15669967],
       [0.14088724, 0.75708028, 0.73632492, 0.35566309, 0.34109302]])

In [177]:
j.sum()

7.164822899895267

### Repaso Algebra Lineal con NumPy

In [178]:
row = [1,2,3]
row

[1, 2, 3]

In [180]:
col = [[1],[2],[3]]
col

[[1], [2], [3]]

In [182]:
M = [[1,2,3],[4,5,6],[7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [222]:
M[0][0] # Ojo esto no es tan facil como cuando tenemos matrices

1.0

In [227]:
M[0] # este para filas

array([1., 2., 3.])

In [225]:
for numero in M:
    print(numero[0]) # para imprimir la primera columna 

1.0
4.0
7.0


In [189]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float) # Ojo
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [190]:
M[0,1] # aqui se puede hacer slicing

2.0

In [191]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [192]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [194]:
np.shape(M)

(3, 3)

In [200]:
A = np.array([[1,2],[3,4]])
print(A)# sumas
B = np.array([[3,0],[1,-1]])
print(B)
print(A+B)

[[1 2]
 [3 4]]
[[ 3  0]
 [ 1 -1]]
[[4 2]
 [4 3]]


In [201]:
print(A.dot(B)) # asi se hacen las multiplicaciones mucho cuidado. 

[[ 5 -2]
 [13 -4]]


In [204]:
print(A.T)

[[1 3]
 [2 4]]


In [206]:
print(A.trace()) # la diagonal 

5


In [207]:
np.linalg.matrix_rank(A) # para ver el rango

2

In [208]:
np.linalg.matrix_power(A,5) # potencias

array([[1069, 1558],
       [2337, 3406]])

In [209]:
np.linalg.det(A) # determinante

-2.0000000000000004

In [211]:
np.linalg.inv(A) # invertida

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [213]:
print(np.linalg.inv(A).dot(A)) # Matriz identidad, ojo. Si es 0,0 pero dada la especificidad de Python
# parece que es no [1,0]
#                  [0,1] pero si es

[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


In [214]:
X = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [215]:
np.linalg.det(X)

-9.51619735392994e-16

In [217]:
np.linalg.matrix_rank(X) # Ojo no esta bien, porque es de rango 3

2

In [219]:
np.linalg.inv(X) # esta matriz no es invertible, ojo con los resultados.

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

Recordar: no hacer una inversa de una matriz cuadrada, ni de una matriz cuyo rango sea inferior a su orden (el numero de filas / columnas de la misma)

In [221]:
# np.linalg.inv(np.array([[1,2,3], [4,5,6]])) 

### Practica: 

#### 1. Cree una función que reciba los tres coeficientes a, b y c para resolver una ecuación de segundo grado. Muestre la solución por pantalla y ayúdese de la biblioteca Math para acceder a la función raíz cuadrada.

In [315]:
import math as mt

def ecuacion_cuadratica ():
    a = int(input("Ingrese el valor de a: "))
    b = int(input("Ingrese el valor de b: "))
    c = int(input("Ingrese el valor de c: "))
    discriminante = mt.pow(b,2)-(4*a*c)
    denominador = (2*a)
    if discriminante > 0:
        x1 = (-b-mt.sqrt(discriminante)) / denominador
        x2 = (-b+mt.sqrt(discriminante)) / denominador
        print("La solucion de la primera x es: %f"%x1)
        print("La solucion de la segunda x es: %f"%x2)
    elif discriminante == 0:
        x0 = -b/denominador 
        print("La solucion doble es respectivamente: %f"%x0)
    else:
        print("El discriminante al ser negativo no tiene ninguna solucion")

In [316]:
ecuacion_cuadratica()

Ingrese el valor de a:  3
Ingrese el valor de b:  6
Ingrese el valor de c:  -7


La solucion de la primera x es: -2.825742
La solucion de la segunda x es: 0.825742


#### 2. Cree una función que lea una frase de teclado y nos diga si es o no un palíndromo (frase que se lee igual de izquierda a derecha o al revés como por ejemplo La ruta nos aportó otro paso natural).

In [331]:
def palindromo(frase):
    limpieza = str.maketrans("áéíóúüñÁÉÍÓÚÜÑ.,;!¡¿?:""''", "aeiouunAEIOUUN          ") # para reemplazar valores
    frase = frase.translate(limpieza) # convertir la frase
    frase = "".join(frase.split()) # junto toda la frase
    frase =frase.lower() # la paso a minusculas 
    if frase == frase[::-1]:
        print("Es palíndromo")
    else:
        print("No es palíndromo")
        
palindromo(input("Ingrese una frase: "))

Ingrese una frase:  La ruta nos aportó otro paso natural


Es palíndromo


#### 3. Cree un diccionario que tenga por claves los números del 1 al 10 y como valores sus raíces cuadradas

In [333]:
import math as mt
diccionario = {"1": mt.sqrt(1),
              "2": mt.sqrt(2),
              "3": mt.sqrt(3),
              "4": mt.sqrt(4),
              "5": mt.sqrt(5),
              "6": mt.sqrt(6),
              "7": mt.sqrt(7),
              "8": mt.sqrt(8),
              "9": mt.sqrt(9),
              "10": mt.sqrt(10)}

In [334]:
print(diccionario)

{'1': 1.0, '2': 1.4142135623730951, '3': 1.7320508075688772, '4': 2.0, '5': 2.23606797749979, '6': 2.449489742783178, '7': 2.6457513110645907, '8': 2.8284271247461903, '9': 3.0, '10': 3.1622776601683795}


#### 4. Cree un diccionario que tenga como claves las letras del alfabeto castellano y como valores los símbolos del código morse (los tiene todos en la Wikipedia). A continuación crea un programa que lea una frase del teclado y la convierta a Morse utilizando el diccionario anterior.

In [338]:
codigo = {
    'A': '.-',     'B': '-...',    'C': '-.-.',
    'D': '-..',    'E': '.',       'F': '..-.',
    'G': '--.',    'H': '....',    'I': '..',
    'J': '.---',   'K': '-.-',     'L': '.-..',
    'M': '--',     'N': '-.',      'O': '---',
    'P': '.--.',   'Q': '--.-',    'R': '.-.',
    'S': '...',    'T': '-',       'U': '..-',
    'V': '...-',   'W': '.--',     'X': '-..-',
    'Y': '-.--',   'Z': '--..',    '1': '.----',
    '2': '..---',  '3': '...--',   '4': '....-',
    '5': '.....',  '6': '-....',   '7': '--...',
    '8': '---..',  '9': '----.',   '0': '-----',
    ' ': '/'
}

frase = input("Ingrese una frase: ")
lista_codigos = [] # necesito crear un array vacio 
for i in frase:
    if i.islower():
        i=i.upper()
    lista_codigos.append(codigo[i])
print (" ".join(lista_codigos))

Ingrese una frase:  esto es un ejemplo en mayuscula


. ... - --- / . ... / ..- -. / . .--- . -- .--. .-.. --- / . -. / -- .- -.-- ..- ... -.-. ..- .-.. .-


In [348]:
codigo = {
    'a': '.-',     'b': '-...',    'c': '-.-.',
    'd': '-..',    'e': '.',       'f': '..-.',
    'g': '--.',    'h': '....',    'i': '..',
    'j': '.---',   'k': '-.-',     'l': '.-..',
    'm': '--',     'n': '-.',      'o': '---',
    'p': '.--.',   'q': '--.-',    'r': '.-.',
    's': '...',    't': '-',       'u': '..-',
    'v': '...-',   'w': '.--',     'x': '-..-',
    'y': '-.--',   'z': '--..',    '1': '.----',
    '2': '..---',  '3': '...--',   '4': '....-',
    '5': '.....',  '6': '-....',   '7': '--...',
    '8': '---..',  '9': '----.',   '0': '-----',
    ' ': '/'
}

frase = input("Ingrese una frase: ")
lista_codigos = [] # necesito crear un array vacio 
for i in frase:
    lista_codigos.append(codigo[i])
print(" ".join(lista_codigos))

Ingrese una frase:  esto es un ejemplo con minusculas


. ... - --- / . ... / ..- -. / . .--- . -- .--. .-.. --- / -.-. --- -. / -- .. -. ..- ... -.-. ..- .-.. .- ...


#### 5. Cree una función que dados dos diccionarios nos diga que claves están presentes en ambos.

In [351]:
lista_supermercado = {'pan':'5','huevos':'3','atun':'1','vino':'3', 'azucar': '1'}
lista_despensa = {'huevos': '4', 'arroz':'6', 'banano':'2', 'jalea':'5'}

for clave in lista_supermercado.keys() & lista_despensa.keys(): # & es para crear la relacion
    print(clave)

huevos


#### 6. Cree una función que dado un número N nos diga si es primo o no (tiene que ir dividiendo por todos los números x comprendidos entre 2 y el propio número N menos uno y ver si el cociente de N/x tiene resto entero o no).

In [362]:
def numeros_primos():
    numero = int(input("Ingrese un número: "))
    if numero > 1:
        for i in range(2,numero):
            if (numero % i) == 0:
                print(numero,"no es un número primo")
                print(i,"por",numero//i,"es",numero)
                break
        else:
            print(numero,"es un número primo")

    else:
        print(numero,"no es un número primo")

In [361]:
numeros_primos()

Ingrese un número:  2


2 es un número primo


#### 7. Investigue la documentación de la clase string y crea un método que lea una frase del teclado y escriba la primera letra de cada palabra en Mayúscula.

In [363]:
frase = str(input("Ingrese una frase: "))
print(frase.title())

Ingrese una frase:  hola como estas?


Hola Como Estas?


#### 8. Cree una función que calcule el máximo común divisor de dos números introducidos por el usuario por teclado.

In [367]:
import math

def mcd():
    a=int(input("Ingrese primer número: "))
    b=int(input("Ingrese segundo número: "))
    mcd = math.gcd(a,b)
    print("El máximo común divisor es %d "%mcd)

In [368]:
mcd()

Ingrese primer número:  6
Ingrese segundo número:  10


El máximo común divisor es 2 


#### 9. Investigue el Cifrado del César y cree una función que lo reproduzca en Python. Cada letra del mensaje original se desplaza tres posiciones en el alfabeto estándar. La A se convierte en la D, la B se convierte en la E, la C se convierte en la F... y cuando se acaba el alfabeto se le vuelve a dar la vuelta: la X se convierte en la A, la Y en la B y la X en la C. Los números no sufren ninguna modificación.



In [369]:
#Pedimos al usuario que ingrese un mensaje
#Se pasa a mayúsculas el mensaje
texto = input("Ingrese un mensaje: ").upper()

#Se puede pedir al usuario que ingrese la cantidad de desplazamientos de posisiciones:
#para el caso del ejercicio, definiremos n=3 que es la premisa dada 
n=3

#Se define abecedario a cifrar
abc = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ"

#Crear variable para guardar el mensaje cifrado
cifrado = ""

#Se itera por cada letra del mensaje
for l in texto:
    #Si la letra está en el abecedario se reemplaza
    if l in abc:
        pos_letra = abc.index(l)
        #Sumamos para movernos a la derecha del abc
        #Se usa la expresión de cálculo del resto, para dar la vuelta al alfabeto (por ej con XYZ)
        nueva_pos = (pos_letra + n) % len(abc)
        #La siguiente expresión "cifrado+= abc[nueva_pos]" es equivalente a escribir "cifrado = cifrado + abc[nueva_pos]"
        cifrado+= abc[nueva_pos]
    else:
        #Si no está en el abecedario (por ejemplo números, letras con tilde, etc), se añade tal cual estaba escrito en el mensaje original
        cifrado+= l

print("Mensaje cifrado:", cifrado)

Ingrese un mensaje:  hola como estas


Mensaje cifrado: KRÑD FROR HVWDV


#### 10. Dado una lista de nombres de persona, escribe un algoritmo que los ordene de tres formas diferentes:

A. De forma alfabética

B. De forma alfabética invertida

C. De nombre más corto al más largo.

In [370]:
Lista=["Heiner","Katty","Roy","Katherine"]

#Lista ordenada de forma alfabética
Lista.sort()
print(Lista)

#Lista ordenada de forma alfabética inversa
Lista.sort(reverse=True)
print(Lista)

#Lista ordenada de nombre más corto a más largo
Lista.sort(key=len)
print(Lista)

['Heiner', 'Katherine', 'Katty', 'Roy']
['Roy', 'Katty', 'Katherine', 'Heiner']
['Roy', 'Katty', 'Heiner', 'Katherine']
